faq_data = [
    # Solar Panel Technology
    ("What is solar energy?", "Solar energy is the energy obtained from the Sun's radiation. Solar panels convert this light into electricity using photovoltaic cells made from semiconductor materials like silicon."),
    ("How do solar panels work?", "Solar panels contain photovoltaic cells that convert sunlight into electricity. When sunlight hits these cells, it excites electrons and generates direct current (DC) electricity. An inverter converts DC to alternating current (AC), which can be used in homes or businesses."),
    ("What types of solar panels are there?", "Monocrystalline Solar Panels: Made from a single crystal structure, these are highly efficient and have a longer lifespan. Polycrystalline Solar Panels: Made from multiple silicon crystals, these are less efficient but more cost-effective. Thin-Film Solar Panels: Made from non-silicon materials, these are lightweight and flexible but less efficient than crystalline panels."),
    ("What is the efficiency of solar panels?", "Solar panel efficiency typically ranges from 15% to 22%, meaning the percentage of sunlight that is converted into usable electricity. High-efficiency panels, such as monocrystalline, can achieve efficiencies above 20%."),
    ("What is the lifespan of solar panels?", "Solar panels typically last 25 to 30 years, with a slight reduction in efficiency each year. Most manufacturers offer warranties of 20-25 years for their panels."),
    ("What is the difference between monocrystalline and polycrystalline panels?", "Monocrystalline panels are more efficient and durable but come at a higher cost. Polycrystalline panels are less efficient but more affordable, making them a good choice for budget-conscious buyers."),

    # Installation Processes
    ("What is the process of installing solar panels?", "1. Site Assessment: A professional assesses the roof's condition, orientation, and available space. 2. Design: A system is designed based on energy needs and available space. 3. Permits: Obtain necessary permits from local authorities. 4. Installation: Solar panels, inverters, and other equipment are installed on the roof. 5. Inspection: The system is inspected to ensure it meets safety and performance standards. 6. Connection: The system is connected to the grid or a standalone battery."),
    ("Can solar panels be installed on all types of roofs?", "Solar panels can be installed on most types of roofs, including flat and sloped roofs. However, the material and condition of the roof, as well as its orientation and shading, play a significant role in determining the feasibility and efficiency of installation."),
    ("How long does it take to install solar panels?", "The installation process usually takes 1-3 days, depending on the system size and complexity. Permitting and inspection can add additional time to the overall timeline."),
    ("What are the common installation challenges?", "Shading: Roofs with significant shading may not be ideal for solar installations. Roof Condition: A roof in poor condition may need repairs before solar panels can be installed. Structural Considerations: The roof must be able to support the weight of the panels."),

    # Maintenance Requirements
    ("What maintenance is required for solar panels?", "Solar panels require very little maintenance. Basic maintenance includes: 1. Cleaning: Periodic cleaning to remove dirt, debris, or bird droppings. 2. Inspection: Regular checks of the system for any damages or issues. 3. Inverter Maintenance: Inverters typically need occasional checks to ensure they’re functioning properly."),
    ("How often should solar panels be cleaned?", "Solar panels should be cleaned 1-2 times a year, depending on the dust and debris accumulation in your area. In areas with heavy rain, cleaning might not be necessary as rain will clean the panels."),
    ("Do solar panels need to be serviced regularly?", "Solar panels are generally maintenance-free, but it’s important to have them inspected every 1-2 years to ensure everything is working optimally, including the inverter and wiring."),

    # Cost & ROI Analysis
    ("How much does it cost to install solar panels?", "The cost of installing solar panels depends on the system size, location, and the type of panels used. On average, residential solar systems cost between $10,000 and $30,000 before incentives."),
    ("What is the ROI of solar panels?", "The return on investment (ROI) depends on factors like the cost of installation, energy savings, and local incentives. On average, residential solar panels can pay for themselves within 7-10 years. After that, they continue to provide savings for decades."),
    ("What incentives are available for solar installations?", "Federal Tax Credit (ITC): The U.S. government offers a 26% tax credit for solar installations (as of 2025). State Rebates: Many states provide rebates to offset installation costs. Net Metering: Allows you to sell excess electricity back to the grid for credits."),
    ("How does net metering work?", "Net metering allows solar panel owners to sell excess electricity generated during the day back to the grid. This generates credits on the electricity bill, which can be used when the system isn’t producing enough electricity (e.g., at night)."),
    ("What is the payback period for solar panels?", "The average payback period for a solar panel system is 7-10 years. The payback period depends on the system cost, local electricity rates, and how much electricity is generated by the system."),

    # Industry Regulations
    ("Are there any regulations regarding solar panel installations?", "Yes, solar panel installations are regulated by local governments, building codes, and safety standards. Regulations may include permit requirements, system specifications, and grid connection standards."),
    ("What is the role of the National Electrical Code (NEC) in solar panel installations?", "The NEC provides guidelines for safe installation practices, including proper wiring, grounding, and system disconnects to prevent electrical hazards."),
    ("Do I need a permit to install solar panels?", "In most areas, a permit is required to install solar panels. The permit ensures the installation complies with local building codes and safety standards."),

    # Market Trends
    ("What are the current trends in the solar energy market?", "Growth in Solar Adoption: Solar energy adoption continues to grow due to falling costs, increased awareness, and government incentives. Battery Storage: More solar systems are being paired with battery storage to provide power during outages or at night. Smart Solar: Solar systems are increasingly incorporating smart technology for monitoring performance and efficiency."),
    ("How is the solar industry evolving?", "The solar industry is moving toward more efficient panels, energy storage solutions, and integration with smart grid systems. Additionally, more countries are committing to renewable energy goals, which is driving further growth in solar power."),
    ("What is the global market for solar energy?", "The global solar energy market is expected to grow at a compound annual growth rate (CAGR) of over 20% from 2023 to 2030. Solar energy is becoming a dominant form of renewable energy, particularly in countries like China, the U.S., and India."),
    ("What are the challenges faced by the solar industry?", "Intermittency: Solar energy generation is intermittent, making it challenging to provide a constant energy supply. Storage Costs: Battery storage is expensive, and current solutions have limited capacity. Regulatory Barriers: In some regions, regulatory and policy barriers hinder solar adoption."),
]
